import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { SUBSCRIPTION_PLANS, type SubscriptionTier } from "@/shared/subscription-plans";

type PurchasableTier = "pro_monthly" | "pro_annual" | "lifetime";

export function SubscriptionPaywall({ visible, isArabic, onClose, onCheckout }: { visible: boolean; isArabic: boolean; onClose: () => void; onCheckout: (tier: PurchasableTier) => void }) {
  const plans: PurchasableTier[] = ["pro_monthly", "pro_annual", "lifetime"];
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.handle} /><View style={styles.head}><View style={styles.icon}><MaterialIcons name="workspace-premium" size={23} color="#07111F" /></View><Pressable onPress={onClose} style={styles.close}><MaterialIcons name="close" size={20} color="#9DB0C4" /></Pressable><View style={{ flex: 1 }}><Text style={styles.title}>{isArabic ? "افتح كامل قوة OMNI LIFE" : "Unlock the full OMNI LIFE"}</Text><Text style={styles.subtitle}>{isArabic ? "لا إعلانـات، قوالب إضافية، ورؤى متقدمة لحياتك اليومية." : "No ads, more templates, and advanced insights for daily life."}</Text></View></View><ScrollView contentContainerStyle={styles.plans} showsVerticalScrollIndicator={false}>{plans.map((tier) => <PlanCard key={tier} tier={tier} isArabic={isArabic} onCheckout={() => onCheckout(tier)} />)}<Text style={styles.manual}>{isArabic ? "دفع يدوي آمن: حوّل عبر InstaPay أو Vodafone Cash، ثم أرفق الإيصال. يراجع المدير الطلب عبر Telegram." : "Secure manual payment: transfer via InstaPay or Vodafone Cash, then attach your receipt for Telegram review."}</Text></ScrollView></View></View></Modal>;
}

function PlanCard({ tier, isArabic, onCheckout }: { tier: PurchasableTier; isArabic: boolean; onCheckout: () => void }) {
  const plan = SUBSCRIPTION_PLANS[tier];
  const lifetime = tier === "lifetime";
  const annual = tier === "pro_annual";
  const duration = tier === "pro_monthly" ? (isArabic ? "شهريًا" : "per month") : annual ? (isArabic ? "سنويًا" : "per year") : (isArabic ? "دفعة واحدة" : "one payment");
  return <View style={[styles.plan, lifetime && styles.lifetime]}>{lifetime ? <View style={styles.badge}><MaterialIcons name="auto-awesome" size={12} color="#062C3A" /><Text style={styles.badgeText}>{isArabic ? "الأكثر توفيرًا" : "Most Popular"}</Text></View> : null}<View style={styles.planTop}><View style={{ flex: 1 }}><Text style={styles.planTitle}>{tier === "pro_monthly" ? "Pro Monthly" : tier === "pro_annual" ? "Pro Annual" : "Lifetime"}</Text><Text style={styles.features}>{tier === "lifetime" ? (isArabic ? "وصول كامل + ميزات حصرية + بدون إعلانات" : "Full access, exclusive features, no ads") : (isArabic ? "وصول كامل + بدون إعلانات + قوالب إضافية" : "Full access, no ads, extra templates")}</Text></View><Text style={styles.price}>{plan.priceEgp} <Text style={styles.currency}>EGP</Text></Text></View>{plan.savingsText ? <View style={styles.savings}><MaterialIcons name="savings" size={13} color="#4FE1A8" /><Text style={styles.savingsText}>{plan.savingsText}</Text></View> : <Text style={styles.duration}>{duration}</Text>}<Pressable onPress={onCheckout} style={[styles.checkout, lifetime && styles.lifetimeCheckout]}><MaterialIcons name="lock-open" size={16} color="#07111F" /><Text style={styles.checkoutText}>{isArabic ? "اشترك الآن" : "Subscribe now"}</Text></Pressable></View>;
}

export const premiumStyles = StyleSheet.create({});
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(2,8,15,0.72)" }, sheet: { maxHeight: "91%", paddingHorizontal: 17, paddingTop: 10, paddingBottom: 26, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: "#07111F", borderWidth: 1, borderColor: "rgba(56,216,255,0.32)" }, handle: { alignSelf: "center", width: 40, height: 4, borderRadius: 4, backgroundColor: "#2A4960", marginBottom: 15 }, head: { flexDirection: "row", alignItems: "flex-start", gap: 10, marginBottom: 17 }, icon: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#38D8FF" }, close: { width: 36, height: 36, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#102035" }, title: { color: "#F3F8FC", fontSize: 17, lineHeight: 24, fontWeight: "900", textAlign: "right" }, subtitle: { color: "#9DB0C4", fontSize: 10, lineHeight: 15, marginTop: 3, textAlign: "right" }, plans: { gap: 11 }, plan: { gap: 10, padding: 13, borderRadius: 17, backgroundColor: "#102035", borderWidth: 1, borderColor: "#1C3B56", overflow: "hidden" }, lifetime: { borderColor: "rgba(56,216,255,0.80)", backgroundColor: "#0D2B3D", shadowColor: "#38D8FF", shadowOpacity: 0.15, shadowRadius: 12 }, badge: { alignSelf: "flex-start", paddingHorizontal: 8, minHeight: 25, borderRadius: 9, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 4, backgroundColor: "#4FE1A8" }, badgeText: { color: "#062C3A", fontSize: 9, fontWeight: "900" }, planTop: { flexDirection: "row", gap: 8, alignItems: "flex-start" }, planTitle: { color: "#F3F8FC", fontSize: 14, fontWeight: "900", textAlign: "right" }, features: { color: "#9DB0C4", fontSize: 9, lineHeight: 14, marginTop: 3, textAlign: "right" }, price: { color: "#38D8FF", fontSize: 19, fontWeight: "900" }, currency: { fontSize: 9 }, savings: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", gap: 4 }, savingsText: { color: "#4FE1A8", fontSize: 9, fontWeight: "900" }, duration: { color: "#9DB0C4", fontSize: 9, textAlign: "right" }, checkout: { minHeight: 42, borderRadius: 11, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6, backgroundColor: "#38D8FF" }, lifetimeCheckout: { backgroundColor: "#4FE1A8" }, checkoutText: { color: "#07111F", fontSize: 11, fontWeight: "900" }, manual: { color: "#91A4B9", fontSize: 9, lineHeight: 15, textAlign: "center", paddingHorizontal: 10, paddingTop: 3 } });
