import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useState } from "react";
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

type Props = { visible: boolean; isArabic: boolean; onClose: () => void; onSave: (entries: string[]) => void };

const colors = { canvas: "#07111F", card: "#101F33", cyan: "#38D8FF", emerald: "#4FE1A8", purple: "#B59CFF", ink: "#F2F7FC", muted: "#91A4B9", border: "#1C3B56" };

export function EveningBrainDumpModal({ visible, isArabic, onClose, onSave }: Props) {
  const t = (ar: string, en: string) => isArabic ? ar : en;
  const [entries, setEntries] = useState(["", "", ""]);
  const [saved, setSaved] = useState(false);
  useEffect(() => { if (visible) { setEntries(["", "", ""]); setSaved(false); } }, [visible]);
  const submit = () => { const clean = entries.map((entry) => entry.trim()).filter(Boolean); if (!clean.length) return; onSave(clean); setSaved(true); };

  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.card}>{saved ? <View style={styles.saved}><View style={styles.moon}><MaterialIcons name="nights-stay" size={28} color={colors.purple} /></View><Text style={styles.savedTitle}>{t("تم حفظ كل شيء بأمان", "Everything is safely saved")}</Text><Text style={styles.savedCopy}>{t("عقلك حر الآن، نوم هادئ 🌙", "Your mind is free now. Sleep gently. 🌙")}</Text><Pressable onPress={onClose} style={styles.closeSaved}><Text style={styles.closeSavedText}>{t("إغلاق الجلسة", "Close ritual")}</Text></Pressable></View> : <><View style={styles.head}><View style={styles.moon}><MaterialIcons name="nights-stay" size={22} color={colors.purple} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{t("تفريغ الذهن", "Evening brain dump")}</Text><Text style={styles.subtitle}>{t("اكتب حتى 3 أفكار أو مهام تشغل بالك للغد. سنحفظها كمهام هادئة.", "Write up to 3 thoughts or tasks for tomorrow. We’ll save them as calm tasks.")}</Text></View></View><View style={styles.inputs}>{entries.map((entry, index) => <View key={index} style={styles.inputRow}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><TextInput value={entry} onChangeText={(value) => setEntries((current) => current.map((item, itemIndex) => itemIndex === index ? value : item))} maxLength={160} placeholder={t("ما الذي تريد أن تتركه هنا؟", "What can you leave here?")} placeholderTextColor={colors.muted} textAlign={isArabic ? "right" : "left"} style={styles.input} returnKeyType="next" /></View>)}</View><Pressable onPress={submit} style={({ pressed }) => [styles.save, pressed && styles.pressed]}><MaterialIcons name="wb-sunny" size={18} color={colors.canvas} /><Text style={styles.saveText}>{t("حفظ للغد وإغلاق اليوم", "Save for tomorrow & close today")}</Text></Pressable><Pressable onPress={onClose} style={styles.skip}><Text style={styles.skipText}>{t("ليس الآن", "Not now")}</Text></Pressable></>}</View></View></Modal>;
}

const styles = StyleSheet.create({
  backdrop: { flex: 1, justifyContent: "center", padding: 22, backgroundColor: "rgba(2,7,15,0.82)" }, card: { borderRadius: 24, padding: 18, backgroundColor: colors.card, borderWidth: 1, borderColor: "rgba(181,156,255,0.34)" }, head: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, moon: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(181,156,255,0.15)" }, title: { color: colors.ink, fontSize: 18, fontWeight: "900", textAlign: "right" }, subtitle: { color: colors.muted, fontSize: 10, lineHeight: 16, marginTop: 4, textAlign: "right" }, inputs: { marginTop: 18, gap: 9 }, inputRow: { flexDirection: "row", alignItems: "center", gap: 8 }, number: { width: 26, height: 26, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(56,216,255,0.11)" }, numberText: { color: colors.cyan, fontSize: 10, fontWeight: "900" }, input: { flex: 1, minHeight: 44, paddingHorizontal: 11, color: colors.ink, backgroundColor: colors.canvas, borderRadius: 12, borderWidth: 1, borderColor: colors.border, fontSize: 11 }, save: { minHeight: 49, marginTop: 17, borderRadius: 14, backgroundColor: colors.emerald, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, saveText: { color: colors.canvas, fontSize: 11, fontWeight: "900" }, skip: { minHeight: 36, alignItems: "center", justifyContent: "center", marginTop: 6 }, skipText: { color: colors.muted, fontSize: 10, fontWeight: "800" }, saved: { alignItems: "center", paddingVertical: 12, gap: 10 }, savedTitle: { color: colors.ink, fontSize: 19, fontWeight: "900", textAlign: "center" }, savedCopy: { color: colors.muted, fontSize: 12, lineHeight: 19, textAlign: "center" }, closeSaved: { minHeight: 44, paddingHorizontal: 16, marginTop: 3, borderRadius: 13, backgroundColor: "rgba(56,216,255,0.12)", borderWidth: 1, borderColor: "rgba(56,216,255,0.32)", justifyContent: "center" }, closeSavedText: { color: colors.cyan, fontSize: 11, fontWeight: "900" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
