import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";

type Props = { visible: boolean; isArabic: boolean; taskTitle: string; onRecover: () => void; onDismiss: () => void };
const colors = { canvas: "#07111F", card: "#10233A", emerald: "#4FE1A8", cyan: "#38D8FF", ink: "#F2F7FC", muted: "#91A4B9" };

export function ZeroGuiltRecoveryModal({ visible, isArabic, taskTitle, onRecover, onDismiss }: Props) {
  const t = (ar: string, en: string) => isArabic ? ar : en;
  return <Modal transparent visible={visible} animationType="fade" onRequestClose={onDismiss}><View style={styles.backdrop}><View style={styles.card}><View style={styles.icon}><MaterialIcons name="spa" size={27} color={colors.emerald} /></View><Text style={styles.title}>{t("جلسة تعافٍ فوري", "A gentle recovery moment")}</Text><Text style={styles.copy}>{t(`انقطع إيقاع «${taskTitle}»، وهذا لا يلغي أي تقدم سابق. دعنا نعيد البداية بمرونة.`, `“${taskTitle}” slipped out of rhythm, and that does not erase your progress. Let’s restart flexibly.`)}</Text><View style={styles.micro}><MaterialIcons name="auto-awesome" size={17} color={colors.cyan} /><Text style={styles.microText}>{t("سننشئ نسخة أخف بنسبة 50% للغد لتسهيل العودة دون ضغط.", "We’ll create a 50% lighter version for tomorrow so returning feels easier.")}</Text></View><Pressable onPress={onRecover} style={({ pressed }) => [styles.recover, pressed && styles.pressed]}><MaterialIcons name="restart-alt" size={19} color={colors.canvas} /><Text style={styles.recoverText}>{t("إعادة ضبط بمرونة", "Reset with flexibility")}</Text></Pressable><Pressable onPress={onDismiss} style={styles.later}><Text style={styles.laterText}>{t("سأعود إليها لاحقًا", "I’ll return to it later")}</Text></Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "center", padding: 24, backgroundColor: "rgba(2,8,15,0.79)" }, card: { alignItems: "center", gap: 11, padding: 20, borderRadius: 24, backgroundColor: colors.card, borderWidth: 1, borderColor: "rgba(79,225,168,0.35)" }, icon: { width: 60, height: 60, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: "rgba(79,225,168,0.13)" }, title: { color: colors.ink, fontSize: 19, fontWeight: "900", textAlign: "center" }, copy: { color: colors.muted, fontSize: 12, lineHeight: 20, textAlign: "center" }, micro: { width: "100%", flexDirection: "row", alignItems: "flex-start", gap: 7, padding: 10, borderRadius: 13, backgroundColor: "rgba(56,216,255,0.08)" }, microText: { flex: 1, color: colors.ink, fontSize: 10, lineHeight: 16, textAlign: "right" }, recover: { width: "100%", minHeight: 50, marginTop: 3, borderRadius: 15, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 7, backgroundColor: colors.emerald }, recoverText: { color: colors.canvas, fontSize: 12, fontWeight: "900" }, later: { minHeight: 34, paddingHorizontal: 12, justifyContent: "center" }, laterText: { color: colors.muted, fontSize: 10, fontWeight: "800" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] } });
