import { PermissionsAndroid, Platform } from "react-native";
import { parseBankSms } from "./bank-sms-parser";

export type BankSmsTransaction = NonNullable<ReturnType<typeof parseBankSms>>;
type DeviceSms = { _id?: number | string; address?: string; date?: number | string; body?: string };
export type SmsScanResult = { status: "imported"; transactions: BankSmsTransaction[]; scanned: number } | { status: "unsupported" | "unavailable" | "denied" | "failed"; transactions: []; scanned: 0 };

export async function requestBankSmsPermission(): Promise<"granted" | "denied" | "unsupported"> { if (Platform.OS !== "android") return "unsupported"; const current = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.READ_SMS); if (current) return "granted"; const result = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_SMS, { title: "تتبع المصروفات عبر الرسائل البنكية", message: "سيحلل OMNI LIFE الرسائل البنكية محليًا لاستخراج المعاملات فقط. لا يرسل أو يحذف أي رسالة.", buttonPositive: "السماح", buttonNegative: "ليس الآن" }); return result === PermissionsAndroid.RESULTS.GRANTED ? "granted" : "denied"; }
function listSms(filter: Record<string, unknown>): Promise<DeviceSms[]> { return new Promise((resolve, reject) => { try { const SmsAndroid = require("react-native-get-sms-android"); if (!SmsAndroid?.list) { resolve([]); return; } SmsAndroid.list(JSON.stringify(filter), (error: unknown) => reject(error), (_count: number, messages: string) => { try { resolve(JSON.parse(messages) as DeviceSms[]); } catch (error) { reject(error); } }); } catch (error) { reject(error); } }); }
/** Reads only a recent, bank-keyword-filtered Android inbox slice after explicit consent. */
export async function scanRecentBankSms(): Promise<SmsScanResult> { if (Platform.OS !== "android") return { status: "unsupported", transactions: [], scanned: 0 }; const permission = await requestBankSmsPermission(); if (permission !== "granted") return { status: permission, transactions: [], scanned: 0 }; try { const messages = await listSms({ box: "inbox", minDate: Date.now() - 30 * 24 * 60 * 60 * 1000, bodyRegex: "(?i).*(purchase|withdrawal|debit|credit|deposit|EGP|مشتريات|شراء|سحب|خصم|إيداع|تحويل|ج\\.?\\s*م\\.?).*", indexFrom: 0, maxCount: 80 }); const transactions = messages.map(parseBankSms).filter((item): item is BankSmsTransaction => Boolean(item)); return { status: "imported", transactions, scanned: messages.length }; } catch (error) { console.warn("[BankSms] Local scan failed", error); return { status: "failed", transactions: [], scanned: 0 }; } }
